version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: keycloak-db-inst
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keycloak_db
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    networks:
      - keycloak-postgres-network

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    container_name: keycloak-inst
    env_file:
      - ./.env
    volumes:
      - ./docker/keycloak/realms:/tmp/real ms
    #    command:
    #      - "-Dkeycloak.migration.action=import"
    #      - "-Dkeycloak.migration.provider=singleFile"
    #      - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
    #      - "-Dkeycloak.migration.file=/tmp/realms/realms-settings.json"
    # entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
    command: start-dev
    ports:
      - "8083:8080"
    restart: always
    depends_on:
      - postgres
    networks:
      - keycloak-postgres-network

networks:
  keycloak-postgres-network:
    driver: bridge
